server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework

mailgun:
  domain: ${MAIL_DOMAIN}
  api-key: ${API_KEY_MAIL}
  from: ${FROM_EMAIL}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:true}
      repositories:
        enabled: false

  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.default_schema: vision
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 10000
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cache:
    type: redis

app:
  cors:
    allowed-origins:
      - https://fiege-vision.com
      - https://www.fiege-vision.com

file:
  upload:
    max-size: 104857600
    max-count: 10

logging:
  level:
    root: INFO
    org:
      springframework:
        security: ERROR
        web: ERROR
        security.web: ERROR
        security.web.authentication.AbstractAuthenticationProcessingFilter: OFF
  file:
    name: src/main/resources/logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8080

pagination:
  max-page-size: 100

tokenSecret: ${TOKEN_SECRET}