INSERT INTO vision.site (name, place, user_id)
VALUES ('GD', 'Gardno', 'System'),
       ('GDA', 'Olsztynek', 'System'),
       ('IDC', 'Łozienica', 'System');

INSERT INTO vision.phone_email_type_supervisor (name, user_id)
VALUES ('Work', 'System'),
       ('Mobile', 'System'),
       ('Private', 'System');

INSERT INTO vision.role (name, weight, user_id)
VALUES ('Admin', 999, 'System'),
       ('Operations Manager', 75, 'System'),
       ('Manager', 50, 'System'),
       ('Team Leader', 29, 'System'),
       ('HR Specialist', 4, 'System'),
       ('Mentor', 2, 'System'),
       ('User', 1, 'System');

DO $$
    DECLARE
        gd_id INT;
        gda_id INT;
        idc_id INT;
    BEGIN
        SELECT id INTO gd_id FROM vision.site WHERE name = 'GD';
        SELECT id INTO gda_id FROM vision.site WHERE name = 'GDA';
        SELECT id INTO idc_id FROM vision.site WHERE name = 'IDC';

        INSERT INTO vision.shift(name, site_id, user_id)
        VALUES ('A', gd_id, 'System'),
               ('B', gd_id, 'System'),
               ('ADM', gd_id, 'System'),
               ('Night', gd_id, 'System'),
               ('Parents', gd_id, 'System'),
               ('A', gda_id, 'System'),
               ('B', gda_id, 'System'),
               ('ADM', gda_id, 'System'),
               ('A', idc_id, 'System'),
               ('B', idc_id, 'System'),
               ('ADM', idc_id, 'System');


        INSERT INTO vision.team(name, site_id, user_id)
        VALUES ('A', gd_id, 'System'),
               ('B', gd_id, 'System'),
               ('C', gd_id, 'System'),
               ('D', gd_id, 'System'),
               ('E', gd_id, 'System'),
               ('F', gd_id, 'System'),
               ('G', gd_id, 'System'),
               ('H', gd_id, 'System'),
               ('R', gd_id, 'System'),
               ('J', gd_id, 'System'),
               ('N', gd_id, 'System'),
               ('QA', gd_id, 'System'),
               ('QB', gd_id, 'System'),
               ('FL', gd_id, 'System'),
               ('ADM', gd_id, 'System'),
               ('A', gda_id, 'System'),
               ('B', gda_id, 'System'),
               ('C', gda_id, 'System'),
               ('D', gda_id, 'System'),
               ('E', gda_id, 'System'),
               ('F', gda_id, 'System'),
               ('G', gda_id, 'System'),
               ('ADM', gda_id, 'System'),
               ('H', gda_id, 'System'),
               ('A', idc_id, 'System'),
               ('B', idc_id, 'System'),
               ('C', idc_id, 'System'),
               ('D', idc_id, 'System'),
               ('E', idc_id, 'System'),
               ('F', idc_id, 'System'),
               ('G', idc_id, 'System'),
               ('ADM', idc_id, 'System'),
               ('H', idc_id, 'System');

        INSERT INTO vision.department(name, site_id, user_id)
        VALUES ('Unloading', gd_id, 'System'),
               ('Shipping', gd_id, 'System'),
               ('Receive', gd_id, 'System'),
               ('Pick/Stow', gd_id, 'System'),
               ('Parents', gd_id, 'System'),
               ('Sort/Pack', gd_id, 'System'),
               ('Return', gd_id, 'System'),
               ('Quality', gd_id, 'System'),
               ('Workflow', gd_id, 'System'),
               ('Administration', gd_id, 'System'),
               ('Unloading', gda_id, 'System'),
               ('Shipping', gda_id, 'System'),
               ('Receive', gda_id, 'System'),
               ('Pick/Stow', gda_id, 'System'),
               ('Sort/Pack', gda_id, 'System'),
               ('Return', gda_id, 'System'),
               ('Quality', gda_id, 'System'),
               ('Administration', gda_id, 'System'),
               ('Unloading', idc_id, 'System'),
               ('Shipping', idc_id, 'System'),
               ('Receive', idc_id, 'System'),
               ('Pick/Stow', idc_id, 'System'),
               ('Sort/Pack', idc_id, 'System'),
               ('Return', idc_id, 'System'),
               ('Quality', idc_id, 'System'),
               ('Administration', idc_id, 'System');

        INSERT INTO vision.shift_time_work(name, shift_code, start_shift, end_shift, site_id, user_id)
        VALUES ('First', 'I','05:45:00','14:00:00', gd_id, 'System'),
               ('Second','II','14:00:00','22:15:00', gd_id, 'System'),
               ('Night','III','21:30:00','05:45:00', gd_id, 'System'),
               ('Parent','R','08:00:00', '16:00:00', gd_id, 'System'),
               ('Day off','W','00:00:00', '00:00:00', gd_id, 'System');


        INSERT INTO vision.position(name, site_id, user_id)
        VALUES ('Warehouseman', gd_id, 'System'),
               ('Quality Specialist', gd_id, 'System'),
               ('Support', gd_id, 'System'),
               ('PWTZ', gd_id, 'System'),
               ('Mentor', gd_id, 'System'),
               ('Problem Solver', gd_id, 'System'),
               ('Senior Problem Solver', gd_id, 'System'),
               ('Team Leader', gd_id, 'System'),
               ('First Level Support', gd_id, 'System'),
               ('Area Managers', gd_id, 'System'),
               ('Workflow', gd_id, 'System'),
               ('Administration Specialist', gd_id, 'System'),
               ('Senior Controlling Specialist', gd_id, 'System'),
               ('Independent Accountant', gd_id, 'System'),
               ('Quality Engineer', gd_id, 'System'),
               ('Quality Manager', gd_id, 'System'),
               ('External Services Manager', gd_id, 'System'),
               ('Purchasing Manager', gd_id, 'System'),
               ('External Services Specialist', gd_id, 'System'),
               ('External Maintenance Specialist', gd_id, 'System'),
               ('Security Manager', gd_id, 'System'),
               ('HR and Payroll Manager', gd_id, 'System'),
               ('Process Specialist', gd_id, 'System'),
               ('HR Manager', gd_id, 'System'),
               ('Senior HR Specialist', gd_id, 'System'),
               ('HR Specialist', gd_id, 'System'),
               ('Junior HR Specialist', gd_id, 'System'),
               ('Translator', gd_id, 'System'),
               ('Senior HR and Payroll Specialist', gd_id, 'System'),
               ('HR and Payroll Specialist', gd_id, 'System'),
               ('Data Analysis Specialist', gd_id, 'System'),
               ('Health and Safety Manager', gd_id, 'System'),
               ('Health and Safety Specialist', gd_id, 'System'),
               ('Health and Safety Inspector', gd_id, 'System'),
               ('Employer Brand Manager', gd_id, 'System'),
               ('Operation Managers', gd_id, 'System'),
               ('HR Site Managers', gd_id, 'System'),
               ('Site Managers', gd_id, 'System'),
               ('Warehouseman', gda_id, 'System'),
               ('Quality Specialist', gda_id, 'System'),
               ('Support', gda_id, 'System'),
               ('PWTZ', gda_id, 'System'),
               ('Mentor', gda_id, 'System'),
               ('Problem Solver', gda_id, 'System'),
               ('Senior Problem Solver', gda_id, 'System'),
               ('Team Leader', gda_id, 'System'),
               ('First Level Support', gda_id, 'System'),
               ('Area Managers', gda_id, 'System'),
               ('Workflow', gda_id, 'System'),
               ('Administration Specialist', gda_id, 'System'),
               ('Senior Controlling Specialist', gda_id, 'System'),
               ('Independent Accountant', gda_id, 'System'),
               ('Quality Engineer', gda_id, 'System'),
               ('Quality Manager', gda_id, 'System'),
               ('External Services Manager', gda_id, 'System'),
               ('Purchasing Manager', gda_id, 'System'),
               ('External Services Specialist', gda_id, 'System'),
               ('External Maintenance Specialist', gda_id, 'System'),
               ('Security Manager', gda_id, 'System'),
               ('HR and Payroll Manager', gda_id, 'System'),
               ('Process Specialist', gda_id, 'System'),
               ('HR Manager', gda_id, 'System'),
               ('Senior HR Specialist', gda_id, 'System'),
               ('HR Specialist', gda_id, 'System'),
               ('Junior HR Specialist', gda_id, 'System'),
               ('Translator', gda_id, 'System'),
               ('Senior HR and Payroll Specialist', gda_id, 'System'),
               ('HR and Payroll Specialist', gda_id, 'System'),
               ('Data Analysis Specialist', gda_id, 'System'),
               ('Health and Safety Manager', gda_id, 'System'),
               ('Health and Safety Specialist', gda_id, 'System'),
               ('Health and Safety Inspector', gda_id, 'System'),
               ('Employer Brand Manager', gda_id, 'System'),
               ('Operation Managers', gda_id, 'System'),
               ('HR Site Managers', gda_id, 'System'),
               ('Site Managers', gda_id, 'System'),
               ('Warehouseman', idc_id, 'System'),
               ('Quality Specialist', idc_id, 'System'),
               ('Support', idc_id, 'System'),
               ('PWTZ', idc_id, 'System'),
               ('Mentor', idc_id, 'System'),
               ('Problem Solver', idc_id, 'System'),
               ('Senior Problem Solver', idc_id, 'System'),
               ('Team Leader', idc_id, 'System'),
               ('First Level Support', idc_id, 'System'),
               ('Area Managers', idc_id, 'System'),
               ('Workflow', idc_id, 'System'),
               ('Administration Specialist', idc_id, 'System'),
               ('Senior Controlling Specialist', idc_id, 'System'),
               ('Independent Accountant', idc_id, 'System'),
               ('Quality Engineer', idc_id, 'System'),
               ('Quality Manager', idc_id, 'System'),
               ('External Services Manager', idc_id, 'System'),
               ('Purchasing Manager', idc_id, 'System'),
               ('External Services Specialist', idc_id, 'System'),
               ('External Maintenance Specialist', idc_id, 'System'),
               ('Security Manager', idc_id, 'System'),
               ('HR and Payroll Manager', idc_id, 'System'),
               ('Process Specialist', idc_id, 'System'),
               ('HR Manager', idc_id, 'System'),
               ('Senior HR Specialist', idc_id, 'System'),
               ('HR Specialist', idc_id, 'System'),
               ('Junior HR Specialist', idc_id, 'System'),
               ('Translator', idc_id, 'System'),
               ('Senior HR and Payroll Specialist', idc_id, 'System'),
               ('HR and Payroll Specialist', idc_id, 'System'),
               ('Data Analysis Specialist', idc_id, 'System'),
               ('Health and Safety Manager', idc_id, 'System'),
               ('Health and Safety Specialist', idc_id, 'System'),
               ('Health and Safety Inspector', idc_id, 'System'),
               ('Employer Brand Manager', idc_id, 'System'),
               ('Operation Managers', idc_id, 'System'),
               ('HR Site Managers', idc_id, 'System'),
               ('Site Managers', idc_id, 'System');

        INSERT INTO vision.county(name, site_id, user_id)
        VALUES ('Poland', gd_id, 'System'),
               ('Belarus', gd_id, 'System'),
               ('Ukraine', gd_id, 'System'),
               ('Georgia', gd_id, 'System'),
               ('Poland', gda_id, 'System'),
               ('Belarus', gda_id, 'System'),
               ('Ukraine', gda_id, 'System'),
               ('Georgia', gda_id, 'System'),
               ('Poland', idc_id, 'System'),
               ('Belarus', idc_id, 'System'),
               ('Ukraine', idc_id, 'System'),
               ('Georgia', idc_id, 'System');

        INSERT INTO vision.agency(name, site_id, user_id)
        VALUES ('APS', gd_id, 'System'),
               ('Bisar', gd_id, 'System'),
               ('Fiege', gd_id, 'System'),
               ('APS', gda_id, 'System'),
               ('Bisar', gda_id, 'System'),
               ('Fiege', gda_id, 'System'),
               ('APS', idc_id, 'System'),
               ('Bisar', idc_id, 'System'),
               ('Fiege', idc_id, 'System');

    END $$;